[package]
name = "anim-bench"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["packages/*"]

[dependencies]
ranim.workspace = true

[workspace.dependencies]
ranim = { path = "../ranim" }
itertools = "0.14.0"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
paste = "1.0"

[[bench]]
name = "scenes"
harness = false
