[project]
name = "anim-bench"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "janim[gui]>=3.0.1",
    "manim>=0.19.0",
    "manimgl",
    "setuptools>=79.0.1",
]

[tool.uv.sources]
manimgl = { path = "manim" }
