[package]
name = "empty"
version = "0.1.0"
edition = "2024"

[dependencies]
ranim.workspace = true
bench_scenes.workspace = true
itertools.workspace = true
pretty_env_logger.workspace = true
log.workspace = true
